### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by kjensenxz** [GeneralUnRest/irssi-mac-notify#1]
When will this script support GNU+Linux and other Unices? :^)

**Comment by kjensenxz** [comment]
also, first

**Comment by ghost** [comment]
I really don't feel like adding an option to such a stupid script I made more out of annoyance than anything else. if you want a libnotify one. I can upload another project, or you can use desktop-notify.pl in the scripts.irssi.org repo.

**Comment by ghost** [comment]
Also an option is just dumb. this script should just be load and forget, not, "o if you're on leenux make sure to configure it."

**Comment by kjensenxz** [comment]
boooooooooooo

**Comment by adedomin** [comment]
I might add it now since I'm stupid and apparently Irssi::pidwait_add exists.

Also using that libnotify script is a bitch if you really don't perl. at all.

..... having two accounts is suffering

**Comment by ghost** [comment]
ok I fixed it.
if you have notify-send it should work for loonix.

however I highly recommend you just use https://github.com/irssi/scripts.irssi.org/blob/master/scripts/desktop-notify.pl instead if you can; this is what I use and it's much faster.
